
CREATE TABLE INGREDIENT(
    INGREDIENT_ID NUMBER,
    NAME VARCHAR2(20),
    PRIMARY KEY(INGREDIENT_ID)
)

CREATE TABLE REVIEW(
    REVIEW_ID NUMBER,
    AUTHOR_FIRST_NAME VARCHAR2(50),
    AUTHOR_LAST_NAME VARCHAR2(50),
    SCORE NUMBER,
    MESSAGE VARCHAR2(500),
    RECIPE_REVIEWED NUMBER,
    PRIMARY KEY(REVIEW_ID),
    FOREIGN KEY(RECIPE_REVIEWED) REFERENCES RECIPE(RECIPE_ID)
)

CREATE TABLE RECIPE(
    RECIPE_ID NUMBER,
    NAME VARCHAR(20),
    CREATOR_FIRST_NAME VARCHAR2(20),
    CREATOR_LAST_NAME VARCHAR2(20),
    DESCRIPTION VARCHAR(500),
    INGREDIENT_ID NUMBER,
    PRIMARY KEY(RECIPE_ID)
)

CREATE TABLE RECIPE_INGREDIENT(
    RECIPE_ID NUMBER,
    INGREDIENT_ID NUMBER,
    PRIMARY KEY(RECIPE_ID, INGREDIENT_ID)
)


CREATE SEQUENCE RECIPE_ID_SEQ MINVALUE 1 INCREMENT BY 1 CACHE 2;
CREATE SEQUENCE INGREDIENT_ID_SEQ MINVALUE 1 INCREMENT BY 1 CACHE 2;
CREATE SEQUENCE REVIEW_ID_SEQ MINVALUE 1 INCREMENT BY 1 CACHE 2;

CREATE OR REPLACE TRIGGER TRIG_RECIPE_ID_SEQ
BEFORE INSERT ON RECIPE FOR EACH ROW
BEGIN
    SELECT RECIPE_ID_SEQ.NEXTVAL INTO :new.RECIPE_ID FROM DUAL;
END;
/
CREATE OR REPLACE TRIGGER TRIG_INGREDIENT_ID_SEQ
BEFORE INSERT ON INGREDIENT FOR EACH ROW
BEGIN
    SELECT INGREDIENT_ID_SEQ.NEXTVAL INTO :new.INGREDIENT_ID FROM DUAL;
END;
/
CREATE OR REPLACE TRIGGER TRIG_REVIEW_ID_SEQ
BEFORE INSERT ON REVIEW FOR EACH ROW
BEGIN
    SELECT REVIEW_ID_SEQ.NEXTVAL INTO :new.REVIEW_ID FROM DUAL;
END;
/